### ISSUE TITLE
Stuck on "Saving World" screen

### ISSUE THREAD

**Issue by pennycan** [ChosenArchitect/Project-Architect-2#162] opened 2024-08-21 18:31 UTC
**Describe the bug**
->Whenever I go the close my world, it now always gets stuck on saving world for 8, 10, 12+ hours.

**To Reproduce**
1. I recently got 2 spirited reactors.
2. Explored a lot more of the world.
3. Closed the game.
4. Got stuck on "Saving World" screen.

**Expected behavior**
->To complete the world save.

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->3.3, 3.4, 3.5
**Java Version**
->jdk-17
**Modpack Launcher Used**
->Prism Launcher
**Ram Allocated**
->10000 mb

**Additional context**
-> There is minor corruption/glitching.

**Comment by hellokingpro109** [comment] 2024-08-22 17:17
I have the same problem, but for me it happen when I change my modpack version to the newer

**Comment by IRicTheCoder** [comment] 2024-08-24 01:53
Can you provide your `lastest.log` from the log folder? It is most likely an error that should be appearing there, so if you could provide the log we can see if it is possible to figure out the issue.

**Comment by hellokingpro109** [comment] 2024-08-24 01:55
Sure, but I can’t send it right now, I’ll do it tomorrow morning.

**Comment by pennycan** [comment] 2024-08-24 03:15
I just provided a little bit of the end since the whole log is too big for Pastebin. 
(https://pastebin.com/1exqhUiz)

**Comment by IRicTheCoder** [comment] 2024-08-30 17:11
> I just provided a little bit of the end since the whole log is too big for Pastebin. (https://pastebin.com/1exqhUiz)

This seems to be an issue with Powah Cables. As for the rest mentioned in this issue, should be solved in 3.6 as many of these issues are caused by Night Config and a fix for it was added.

**Comment by IRicTheCoder** [comment] 2024-09-16 06:23
No more input was given on this after 2 weeks, will close the issue as solved, if needed, reopen the issue.

**Closed as completed by IRicTheCoder** 2024-09-16 06:23 UTC
