### ISSUE TITLE
Error with Firework Rockets

### ISSUE THREAD

**Issue by 12Ooats** [ChosenArchitect/Project-Architect-2#252] opened 2024-09-29 13:08 UTC
**Describe the bug**
->There seems to be an error with Minecraft Fireworks in several instances. I believe they are all tied to the same cause. 
1. Searching Firework Rockets in JEI does not let you view any recipes. But if have a Firework Rocket in your inventory and use the Recipe hotkey it will show up. 
2. The Rocket Mycelial Generator (from Industrial Foregoing: Generators) will only accept Fireworks that contain "Flight Duration" data. Fireworks crafted by 1 Paper and 1 Gunpowder do not contain "Flight Duration" data. 
3. The Sequential Fabricator (from Thermal Expansion) does not recognize 1 Paper and 2 Gunpowder or 1 Paper and 3 Gunpowder as valid recipes for Firework Rockets. 

**To Reproduce**
Steps to reproduce first behavior:
1. Search "Firework" in JEI
2. Left-click mouse or press R key when hovering over any minecraft:firework_rocket or minecraft:firework_star
3. See that no recipe appears. 
4. Craft a Firework Rocket with 1 Paper and 1 Gunpowder.
5. Press R key when hovering over the crafted Firework Rocket. 
6. See that recipe appears. 
7. Craft a Firework Rocket with 1 Paper and 2 Gunpowder or 1 Paper and 3 Gunpowder.
8. Press R key when hovering over the crafted Firework Rocket.
9. See that no recipe appears. 

Steps to reproduce second behavior:
1. Craft a Firework Rocket with 1 Paper and 1 Gunpowder. 
2. Insert crafted Firework Rocket into Rocket Mycelial Generator.
3. See that the generator produces power. 
4. Craft a Firework Rocket with 1 Paper and 2 Gunpowder or 1 Paper and 3 Gunpowder.
5. Attempt to insert crafted Firework Rocket into Rocket Mycelial Generator.
6. See that it does not allow the Firework Rocket to be placed in the generator. 

Steps to reproduce third behavior:
1. Open Sequential Fabricator.
2. Place 1 Paper and 1 Gunpowder in crafting grid. 
3. Click green check to verify recipe.
4. Supply Sequential Fabricator with power, Paper, and Gunpowder.
5. See that Sequential Fabricator begins crafting Firework Rockets. 
6. Add 1 or 2 Gunpowder to crafting grid.
7. Click green check to verify recipe. 
8. Attempt to supply Sequential Fabricator with Paper and Gunpowder. 
9. See that it does not allow the Paper or Gunpowder to be placed in the internal buffer. 

**Expected behavior**
->First behavior: Left-mouse click or R key press on minecraft:firework_rocket should show recipe. 
->Second behavior: Rocket Mycelial Generator should accept any minecraft:firework_rocket. 
->Third behavior: Sequential Fabricator should recognize 1 paper and 2 Gunpowder or 1 paper and 3 Gunpowder as a valid recipe. 

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->3.6
**Java Version**
->1.20.1
**Modpack Launcher Used**
->Curseforge
**Ram Allocated**
->7168MB

**Additional context**
->

**Comment by ChosenArchitect** [comment] 2024-09-29 15:58
The recipes are vanilla. JEI has never showed them and same with the firework stars. You will need to use tier 2 and up I think to get it to work. You will have to set The sequential fabricator by hand to get it to work. It should work given that it doesn't rely on jei to work. It's a vanilla recipe.

**Comment by IRicTheCoder** [comment] 2024-09-29 18:34
Firework is an issue even on vanilla, they never updated that recipe to the datapack system of recipes, what Chosen suggested should work, it should also work with auto crafting in RS or AE2 but you need to set the recipe by hand in the patterns.

**Comment by 12Ooats** [comment] 2024-10-01 10:44
Chosen and Ric thank you for your replies and I understand the JEI part is a vanilla issue. Its possible that the issue I'm encountering is mod-specific and nothing you can fix. I searched and found other people also reporting an issue with RF Tools crafter unable to craft fireworks.  I've attached some screenshots so you can see my problem. 

![2024-10-01_06 14 15](https://github.com/user-attachments/assets/51269c60-3635-4717-808e-9dfd19c19aad)
As you can see I am trying to power the Rocket Mycelial Generator. The left Sequential Fabricator is crafting paper and moving it into a buffer (oak drawer). 

![2024-10-01_06 14 54](https://github.com/user-attachments/assets/0acc90f4-cb32-4c26-8277-de3026b91ba2)
The right Sequential Fabricator is supposed to craft Fireworks but wont accept any inputs (piped, inserted by hand, or otherwise) for that specific crafting recipe. The same happens if I attempt a 1 Paper 3 Gunpowder recipe. I'm setting the crafting recipe by hand, no JEI involved. 

![2024-10-01_06 15 23](https://github.com/user-attachments/assets/2700bf61-7213-49e6-9f7a-d4db5cfdd54b)
Here I changed the recipe for the right Fabricator and it will successfully craft Fireworks for a 1 Paper 1 Gunpowder recipe. It even extracts the items for the adjacent inventories to fill its inventory. 

But the Rocket Mycelial Generator will not accept those Fireworks (piped, inserted by hand, or otherwise). It will only accept Fireworks with "Flight Duration" data, and single gunpowder fireworks don't have that tag. 
![image](https://github.com/user-attachments/assets/545eae3e-806e-4ab0-8451-c21f5c85ddf7)
_*See that the fireworks crafted with 1 gunpowder don't have the "Flight Duration: x" NBT tag_
![image](https://github.com/user-attachments/assets/967729f3-92e6-4ead-ab92-81d98dd2ed26)
_*See that the 2 gunpowder fireworks do have the "Flight Duration: x" NBT tag. And are accepted by the Generator._ 

Let me know what you would recommend?

**Comment by IRicTheCoder** [comment] 2024-10-01 15:50
I would suggest trying other crafters, mainly using Applied Energistics 2 or Refined Storage, I know I have been able to craft them with Refined Storage before.

**Comment by 12Ooats** [comment] 2024-10-01 16:24
I was able to create the system using Refined Storage. It is unfortunate, though, that I cannot create it with a standalone system. Thank you!

**Comment by IRicTheCoder** [comment] 2024-10-04 00:28
A potential fix will come out in a new update, we have made a custom recipe to allow for the firework rockets to be craftable in any autocrafting system. However, this issue is caused by Vanilla minecraft itself and it is not something we can fix beyond adding a custom recipe.

Closing the issue as solved as a solution was found for the issue regardless of the upcoming fix.

**Closed as completed by IRicTheCoder** 2024-10-04 00:28 UTC

**Comment by 12Ooats** [comment] 2024-10-04 13:21
Hi Ric, for the upcoming fix, do I have to through CurseForge and change my modpack to the latest version?

**Comment by IRicTheCoder** [comment] 2024-10-04 13:46
> Hi Ric, for the upcoming fix, do I have to through CurseForge and change my modpack to the latest version?

Once the update comes out with the fix, most likely next version 4.7, you will just have to update, either through curse or a launcher that gets it from curse. Essentially just update like you normally do.

**Comment by 12Ooats** [comment] 2024-10-04 13:48
Ah okay, this would be my first time updating a modpack so thank you!
