### ISSUE TITLE
Certain Mods Cause Game To Not Launch

### ISSUE THREAD

**Issue by ndkean** [ChosenArchitect/Project-Architect-2#234] opened 2024-09-18 06:36 UTC
**Describe the bug**
-> When I use "NoCube's Villagers Sell Animals" and "Quark Delight," the game doesn't start. When both of those mods are disabled, the game starts, but when either one is enabled the game doesn't start.

**To Reproduce**
1. Launch the game with the two mods enabled.

**Expected behavior**
-> The game should launch.

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
-> 4.1
**Java Version**
-> 17.0.7
**Modpack Launcher Used**
-> Prism Launcher (Flatpak)
**Ram Allocated**
-> Tried 8GB and 16GB, neither worked

**Additional context**
-> I'm running Fedora Linux 40 with an AMD GPU and I just ran `dnf upgrade` and rebooted (so my drivers should be up to date). When trying to run the game with either of the two mods enabled the loading screen briefly flashes before crashing. Here is the log:

[log.txt](https://github.com/user-attachments/files/17039536/log.txt)

**Comment by IRicTheCoder** [comment] 2024-09-24 19:43
Could be an issue with Prism Launcher, not sure though, try updating to 4.3 and see if it still happens 4.1 had some weird bugs we fixed on the next versions.

**Comment by IRicTheCoder** [comment] 2024-10-04 00:26
3 updates have been by, no new feedback on this. Based on the log this could be from a corrupt install, caused by Prism Launcher or an issue with the bugs that existed in 4.1. Considered it solved due to lack of feedback, if the issue persists feel free to reopen the issue. Thank you!

**Closed as completed by IRicTheCoder** 2024-10-04 00:26 UTC
Labels: unsure
