### ISSUE TITLE
Client and server pack for 3.5 for MC 1.20.1 mismatch

### ISSUE THREAD

**Issue by SkyeRise** [ChosenArchitect/Project-Architect-2#174] opened 2024-08-24 17:25 UTC
**Describe the bug**
The client and server packs for version 3.5 for Minecraft 1.20.1 are not compatible at all.
->

**To Reproduce**
1. Download modpack with curseforge launcher
2. Use the link to download server pack for the pack in the launcher
3. Install on server, start client
4. Red X for incompatible versions and failure to log in (timeout)

**Expected behavior**
Client and server pack of the same version should work together.
->

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
3.5
->
**Java Version**
17 (also tried 21)
->
**Modpack Launcher Used**
Curseforge
->
**Ram Allocated**
8GB client, 12GB server
->

**Additional context**
->

**Comment by IRicTheCoder** [comment] 2024-08-25 00:55
Did you add any mods, changed any configurations, or installed the client with an instance already open? Because so far there have been no reports about this that I am aware. Sometimes curse download the updated mods and does not remove the old ones, this can cause issues, try with a fresh install of the pack and see if it still happens.

**Comment by SkyeRise** [comment] 2024-08-25 09:48
No to any of these. First time install on both client and server and I got the server pack from the client's link to that and it also stated 3.5 as the version.
The server instance also had other modpacks of both Forge and Fabric working before. Also the server runs without errors and simply does not work with the client of the same version.
I made sure both sides run the exact same forge version as well.

**Comment by IRicTheCoder** [comment] 2024-08-25 11:17
This is in fact a weird thing, haven't seen any reports like this. There might be a mod missing from the server, as when making the server pack client mods need to be taken out, so there might be a chance that a mod got deleted and it shouldn't have. 

The server files from 3.4 should work as long as you copy the Thermal Extras from 3.5 which is an older version that doesn't break older worlds that have already been started.

**Comment by SkyeRise** [comment] 2024-08-25 12:47
There are 297 files in the server mods folder.

**Comment by SkyeRise** [comment] 2024-08-25 12:48
If there is no immediate solution I will simply wait for the next version and try again. Thanks anyway.

**Comment by happenstance-me** [comment] 2024-08-25 15:17
Fresh install of 3.5 PA2 and got the same mismatch.  The issue is that the server has the following two mods and the client does not:
quarkdelight  and  apothic_amendments__enchanting

**Comment by IRicTheCoder** [comment] 2024-08-25 20:52
> Fresh install of 3.5 PA2 and got the same mismatch. The issue is that the server has the following two mods and the client does not: quarkdelight and apothic_amendments__enchanting

Thank you for the info, this is weird, will look into fixing it on the next update.

**Comment by tmacnish** [comment] 2024-08-26 00:07
I am also having this problem. Both versions are 3.5. My server mod list is 297 items while my client has 312. 
![mismatch](https://github.com/user-attachments/assets/3e916c31-6f47-4096-ba96-d0d445675556)
![image](https://github.com/user-attachments/assets/c31aca72-0b1a-4066-a8e3-8f958085eae1)

**Comment by IRicTheCoder** [comment] 2024-08-26 00:11
@tmacnish Remove `quarkdelight` and `apothic_amendments__enchanting` from the server and it should work.

**Comment by tmacnish** [comment] 2024-08-26 00:17
@IRicTheCoder - thank you for the fast response. Sadly I tried that and reloaded my client. still isnt working. I am going to try a fresh install of PA2 and try again.

**Comment by IRicTheCoder** [comment] 2024-08-26 00:21
@tmacnish If you manage to fix it, please let us know, so we are aware of what might have to be fixed on update 3.6

**Comment by tmacnish** [comment] 2024-08-26 01:27
@IRicTheCoder - So removing those 2 mods from the server did not fix the issue. However, removing the 2 mods on BOTH the server as well as the client worked.  apothic_amendments__enchanting & quark_delight. The big red X has not gone away but my friend was able to join the server without getting timed out. (He too had to remove the 2 mods listed above) So currently my client has 310 mods total while the server has 295. Server seems healthy and working fine. Ill update if we run into any bugs. By the way I didnt end up re-installing PA2. Since my buddy freshly installed an hour prior he was my test dummy. 

Would you like screenshots of anything?

**Comment by IRicTheCoder** [comment] 2024-08-26 01:30
@tmacnish Thanks for the reply, can you check if the mods you removed are different versions the one on client and the one on server? Seems that if it works now those might have been the issue, as being different versions.

**Comment by tmacnish** [comment] 2024-08-26 01:33
@IRicTheCoder - Heres a screenshot from my recycle bin. You can see the top 2 are from my client and the bottom 2 are from the server folder. 
![image](https://github.com/user-attachments/assets/58303f6a-0159-4697-9aef-5aa6e6d27be5)

**Comment by IRicTheCoder** [comment] 2024-08-26 02:13
@tmacnish Thank you that is in fact weird, but yeah. Anyways thanks for the feedback.

**Comment by SkyeRise** [comment] 2024-08-28 07:20
I just downgraded to 3.3 and have the exact same issue again. Any other modpack - both forge and fabric - works without issues on both my client and server setup. This one is the first and only doing this.

**Comment by SkyeRise** [comment] 2024-08-28 08:35
It works after removing the same two mods listed above on client and server. However, only the first login in a session ever works. After that I have to restart the client or it crashes very hard (to the point of crashing and freezing task manager trying to stop it).

**Comment by tmacnish** [comment] 2024-08-28 15:33
@SkyeRise - Hey I figured since we are having similar issues I will see if mine does the same. I just got everything booted up and I'm able to connect to server, disconnect, connect, disconnect without issue. I would also like to say that this is the first time I've seen this issue as well. I have created and hosted close to a dozen modded and vanilla servers for my family/friends.

Heres my computer specs or anything that might be useful to help narrow down this issue.

**Computer Specs:**
**Mobo:** Gigabyte Z390 Aorus Pro Wifi
**CPU:** Intel i9-9900k
**GPU:** NVIDIA GeForce RTX 2070 (Geforce Driver Version: 551.23)
(I found the version in the GeForce Experience App under the settings)
**RAM:** (32GB) - 4 x 8GB G.SKILL F4 DDR4 3200 C16
**OS**: Windows 10

**Comment by IRicTheCoder** [comment] 2024-08-28 15:35
Did you guys try to join the server when it said the incompatibility thing? Like just ignore it and join? If you tried it didn't it work?

**Comment by tmacnish** [comment] 2024-08-28 15:36
@IRicTheCoder - Yeah Ric, the big red X is there but you can still connect and so can my buddy. We also tested this with those 2 mods installed but the client would just hang for a while and then fail to connect.

**Comment by tmacnish** [comment] 2024-08-28 15:42
https://drive.google.com/file/d/1FvenX4NVSqjs_jNEGlrRUw5TWHjtZbWM/view?usp=sharing

Here is a video

**Comment by IRicTheCoder** [comment] 2024-08-28 15:48
Thanks for the feedback will try to get what is making that happen, as people have had the X appear but are able to play with no issues.

**Comment by tmacnish** [comment] 2024-08-28 15:49
@IRicTheCoder Thank you for being the man to fix all this stuff. Pretty awesome that theres people like you out there

**Comment by IRicTheCoder** [comment] 2024-08-28 15:56
Well can't take all the credit, ShiftTheDev does a lot too, and already did more than I did, including mods to fix issues that couldn't be fixed other ways. Chosen also does a lot since it is his modpack, so I can't take all the credit. But I appreciate the words.

**Comment by SkyeRise** [comment] 2024-08-29 07:42
@tmacnish - I don't think it has anything to do with hardware though?

I just messed with version 3.5 a bit and got it to work with those two mods removed and also threw in BetterCompatibilityChecker (and did the config for both ends):

![image](https://github.com/user-attachments/assets/177e2b9d-927f-432f-847f-fb56554cdfa4)

Works like a charm and no more red X ugliness :)

EDIT: adding the bcc-common.toml in config folder in case it helps:

#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 1066048
	#The name of the modpack
	modpackName = "Project Architect 2"
	#The version of the modpack
	modpackVersion = "3.5"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

**Comment by IRicTheCoder** [comment] 2024-09-16 06:28
We introduced Better Compatibility Checker which should help handle these cases, closing this as solved. If the same issue reappears feel free to reopen the issue.

**Closed as completed by IRicTheCoder** 2024-09-16 06:28 UTC
Labels: bug
