### ISSUE TITLE
mobs don't make a sound upon dying.

### ISSUE THREAD

**Issue by Dorrivix** [ChosenArchitect/Project-Architect-2#230] opened 2024-09-17 00:57 UTC
**Describe the bug**
-> as described in the title, killing mobs does not cause generic_hurt (the damage tick sound) or their death sounds for any mob that I've tested.

**To Reproduce**
1.  open game
2.  load world
3.  hurt or kill a mob (any)
4. 

**Expected behavior**
->these events should make a sound.

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->4.0
**Java Version**
->17.0.8
**Modpack Launcher Used**
-> Prism
**Ram Allocated**
-> 8GB

**Additional context**
->

**Comment by ChosenArchitect** [comment] 2024-09-17 15:33
Im looking into this and not really sure what Is causing this issue... doing more digging

**Comment by ChosenArchitect** [comment] 2024-09-17 16:04
so after looking I have found the cause and I'm looking into a fix for it!

**Comment by IRicTheCoder** [comment] 2024-09-18 04:56
This is fixed in version 4.1

**Closed as completed by IRicTheCoder** 2024-09-18 04:56 UTC
