### ISSUE TITLE
im so good at finding bugs I might as weel be a bug tracker (texture)

### ISSUE THREAD

**Issue by XenonsTech** [ChosenArchitect/Project-Architect-2#143] opened 2024-08-15 17:38 UTC
**Describe the bug**
-> glitched blitz texture

**To Reproduce**
1.  find a blitz 
2. look at it
3. 
4. 

**Expected behavior**
-> try to fix the texture

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
![2024-08-15_13 35 27](https://github.com/user-attachments/assets/93e171eb-a2f4-403f-b557-3701e93e27aa)
![2024-08-15_13 35 29](https://github.com/user-attachments/assets/a19b32f4-b5c9-4685-a4fc-4ecda0ce99de)

**Modpack version**
-> 3.3
**Java Version**
-> 1.20.1
**Modpack Launcher Used**
-> curseforge
**Ram Allocated**
-> 12gb

**Additional context**
-> It doesnt seem like the one in the nether is glitched it seems fine.

**Comment by shiftthedev** [comment] 2024-08-16 08:47
bug with Thermal and Entity Texture Features

**Comment by XenonsTech** [comment] 2024-08-16 18:27
> bug with Thermal and Entity Texture Features

is there a way to fix it because it was not bugged last time I had played

**Comment by IRicTheCoder** [comment] 2024-08-22 02:07
This bug is random, and it is up to the mods Shift mentioned to fix it, unfortunately fixing it in our side does not seem possible. However this issue is a duplicate of #131 so I will close it as a duplicate.

**Closed as completed by IRicTheCoder** 2024-08-22 02:07 UTC
Labels: duplicate
