### ISSUE TITLE
FPS Drops to 1 randomly

### ISSUE THREAD

**Issue by Skipper-36** [ChosenArchitect/Project-Architect-2#250] opened 2024-09-27 10:41 UTC
**Describe the bug**
-> So i have a problem, that effects my save. Whenever i am getting close to my "base" my FPS drops down to 1, if i fly 100 blocks away they become normal and shoot up to over 100. I dont know what the problem is that causes this issue. This occured not from the beginning of the world save.
If i look at my Task Manager i can see that my graphics card utilization goes down to 5% if i am at my base. If i fly away it goes up to about 40-50%
(Card is a RTX 3080)
Thanks in advance.

**Modpack version**
-> Current 3.6
**Java Version** 
-> Version8 Update 331
**Modpack Launcher Used**
-> curseforge 
**Ram Allocated**
-> 10 GB

**Additional context** (Screenshots)
![2024-09-27_12 35 03](https://github.com/user-attachments/assets/d3a581d8-50c1-4d38-abba-d7fa56eb4ca6)
![2024-09-27_12 35 53](https://github.com/user-attachments/assets/62a343d3-fdc7-48f4-8035-8b94862485ec)

**Comment by ChosenArchitect** [comment] 2024-09-27 11:58
Latest version is 4.4 so if you update and you are still having these issues then we can try and help.

**Comment by Skipper-36** [comment] 2024-09-27 13:20
Thank you, i didnt notice the version updates probably cause im blind. Unfortunatly it did not solve the problem. I noticed that as soon as i exit the menu or settings my GPU Usage falls down. even if i am in the inventory.

**Comment by IRicTheCoder** [comment] 2024-09-27 16:58
What do you have in your base that only works when you are close to it? (Meaning its not in a loaded chunk?)

**Comment by Skipper-36** [comment] 2024-09-27 18:19
I had my base chunkloaded because of a mob farm, and everything worked fine. Just recently the issue started appearing. i tried to remove every new addition but so far nothing worked. even tried to remove the force loading of the chunks still the same problem. 
If that helps

**Comment by IRicTheCoder** [comment] 2024-09-27 18:21
Can you give me a list of the things you added, and how your mob farm is designed? Are you by any chance killings bosses with a Draconic Evolution Mob Grinder?

**Comment by Skipper-36** [comment] 2024-09-28 12:22
So the Mob Farm is made with mobgrinding utils. same concept as the one ChosenArchitect build early in his series. 
The blocks i added were a simple ars noveau setup for infusing, and a farm with the Red fertilizer, The Lilypads which speed up growth and a harvester from cyclic with a Void hopper from Mobgrinding. I removed the farming setup already but it did not help. Also started with the Powah mod. Endercell, Energy Cell, a setup to energize items (3rd tier i think). Also i started a RFTools Builder with a Clearing Fortune Quarry card. But the Builder worked fine the first two times.
Thanks for the help.

**Comment by IRicTheCoder** [comment] 2024-09-28 17:14
Anything else you can think of that might be an issue? Are you using any Kitchen Sinks from Blockheads? Or are you using any EMC Links?

Also you have vsync on, turn it off as OpenGL doesn't handle that the best way, and set the frames to unlimited see if that helps

**Comment by Skipper-36** [comment] 2024-09-28 20:01
I was able to remove the Links and the Sink i was using, but id unfortunatly didnt help, deactivating vsync too. Still got one FPS in my Base, but as soon as i hit ESC the FPS normalizes i dont know why. 
I Screenshoted my Settings if the Problem is in there.
![2024-09-28_22 00 04](https://github.com/user-attachments/assets/08863841-36a5-43ef-adbd-89e8428fe9bd)
![2024-09-28_22 00 07](https://github.com/user-attachments/assets/a3c3c6ca-c188-4ca8-aaff-9f54fa4830e7)
![2024-09-28_22 00 10](https://github.com/user-attachments/assets/dc4fd375-770d-4b70-8e0a-30db5009a2dc)
![2024-09-28_22 00 12](https://github.com/user-attachments/assets/becc909f-0c94-4c88-b59c-8e4b4601c468)

**Comment by IRicTheCoder** [comment] 2024-09-28 20:09
Can you run the command `/forge tps` and send a screenshot of the result? Just to check if the issue is rendering (FPS only) or CPU/Processing (also affects TPS)

**Comment by Skipper-36** [comment] 2024-09-28 20:15
No problem 
![2024-09-28_22 13 44](https://github.com/user-attachments/assets/4126908f-42ae-4dcb-9051-529efe9d36f1)
Hope this helps

**Comment by IRicTheCoder** [comment] 2024-09-28 20:35
Ok so its a problem with processing, as TPS is very low, and it seems to be related to your overworld specifically. Would it be possible to make a list of all machines/things you have working on your base?

**Comment by Skipper-36** [comment] 2024-09-29 12:34
Hi, so it is a tad bit embarrasing and i am so sorry for wasting your time. Apparently my Monster Farm was backed Up by templates from RFTools Dimension and was not picking up any of the monster loot. And it was so much that it lagged out my game like crazy. 
Again i am sorry for not notizing this issue earlier, it was quite hard to walk around at 1FPS.
THank you still for your effort, help and patience.
The Problem solved itself now.

**Comment by IRicTheCoder** [comment] 2024-09-29 18:27
No need to apologize, I also didn't think of that, it happens and I am glad you solved it. Have fun!

Closing the issue as solved.

**Closed as completed by IRicTheCoder** 2024-09-29 18:27 UTC
Labels: question, unsure
