### ISSUE TITLE
Block Absorber not absorbing certain blocks

### ISSUE THREAD

**Issue by Ristoufe** [ChosenArchitect/Project-Architect-2#160] opened 2024-08-21 01:44 UTC
**Describe the bug**
->The block absorber from RFToolsDimensions does not absorb certain types of blocks including high EMC blocks such as compressed blocks (all types of compressed blocks) and matter block (dark matter, red matter, ...). Even though the Block Dimlets are craftable using the Common Lost Knowledge with the pattern "common block" and the reason "mineable/paxel".

**To Reproduce**
1. Take a block absorber
2. Put it on top of any compressed block (for instance a 6 times compressed acacia log)
3. It will not absorb the block
4. 

**Expected behavior**
-> The block should be absorbed by the block absorber

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
-> 3.4
**Java Version**
->
**Modpack Launcher Used**
-> CurseForge
**Ram Allocated**
-> 10Go

**Additional context**
-> I tried making a block absorber that would have absorbed 256 compressed blocks to see if the recipe for the dimlet works and it does. So the only problem is that the blocks are not being absorbed. I have seen reports of this bug from other places on Internet so it surelyy is the fault of the mod itself.

**Comment by IRicTheCoder** [comment] 2024-08-21 05:10
So it seems that when some blocks are disabled in the config, but listed nonetheless, RFTools shows the dimlets but the block absorber doesn't seem to take them in. Not sure if the dimlets are removeable though...

It seems to be a bug from the mod itself.

**Comment by Ristoufe** [comment] 2024-08-21 13:12
So is it voluntary that these blocks are disabled in the config ?

**Comment by Ristoufe** [comment] 2024-08-21 13:14
And if it is voluntary, maybe removing the blocks in the json file would make the dimlet disappear ?

**Comment by IRicTheCoder** [comment] 2024-08-21 18:10
You can edit the json files if you want to add the blocks in. We can't really remove them from the files because otherwise they will naturally appear (randomly) due to another bug in the dimensions.

**Comment by IRicTheCoder** [comment] 2024-08-30 17:13
This has been addressed, the absorbers are working as intended, we are looking for a way to hide the dimlets or display they are disabled, but for all senses this is intended (just a bit bugged due to the mod itself). So closing this as solved.

**Closed as completed by IRicTheCoder** 2024-08-30 17:13 UTC
Labels: intended
