### ISSUE TITLE
Possible Chunk Loading Server Crash in an RFT Dimension?

### ISSUE THREAD

**Issue by ADVM01** [ChosenArchitect/Project-Architect-2#248] opened 2024-09-26 16:13 UTC
**Describe the bug**
-> i was trying to make an EMC farm with the help of a digital miner and the RF tools dimensions mod, using Draconium ore as the Mined resource (note that this machine was not powered nor functional yet), and as with any other machine i wanted to chunk load it via the map. As soon as i chunk loaded the chunk in the RFTD custom dimension, the server crashed and keeps crashing upon joining. Pretty sure this is not a server provider issue since i have a few overworld chunks forceloaded.

**To Reproduce**
- not sure if this will be possible to replicate. My server provider is Aternos FYI
1. make a RFToolsDimensions dimension containing draconium ore(i guess???)
2. try chunk loading a digital miner.
3. 
4. 

**Expected behavior**
-> 

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
-> 4.4
**Java Version**
->Latest as of posting this thread
**Modpack Launcher Used**
-> CurseForge
**Ram Allocated**
-> Server ram is 2GB if i am not mistaken.

**Additional context**
-> server console crash report provided by aternos = https://mclo.gs/OGPFhvu

**Comment by ADVM01** [comment] 2024-09-26 16:44
UPDATE: I managed to delete the RFTD dimension from the server files, and it resolved the server crashing. I will do further testing on the chunk loading part.

**Comment by IRicTheCoder** [comment] 2024-09-26 16:46
Its not an issue with the chunk loading per say, its RFTD corrupting world chunks, when you force load it, the checks crash the server. Also, Aternos forces the ram limit, meaning that too many loaded chunks will start to consume all the RAM and make the TPS very low, so you want to pay some attention to that.

If it happens again let us know, I will leave this open for now. Thanks for the report!

**Comment by ADVM01** [comment] 2024-09-26 16:49
Ah, i understand now, well thanks a lot for the comment, is there any way to load the chunks without crashing? i want the machine to work 24/7 but i guess im out of luck

**Comment by IRicTheCoder** [comment] 2024-09-26 16:53
You can keep doing what you are doing, that case seemed to have a been just corruption on the files, you should not have this issue regularly. Do note that it happens more frequently when the world contains spheres made of grass/dirt like blocks, those tend to corrupt very easily for some reason.

Besides that, you should be able to still chunk load normally, if you crash remove the files and try again, but do provide a report if it does happen again, there might be more to it than what I am currently seeing

**Comment by ADVM01** [comment] 2024-09-26 17:27
So, after a while of playing in the dimension everything seemed fine. It crashed the server again. Crash report: https://mclo.gs/jKeA2bb

i might need to look into the other force loaded chunks although i should only have like 5 or 6 loaded, and the server did not seem to lag or have too little ram to run.

btw, the dimension has no grass spheres, if i am not mistaken its a regular hills biome with some huge dirt squares full of different dirt blocks, and of course the draconium which is in place of almost all stone blocks. Now that i am thinking about it, it might even be those huge dirt blocks. Still more testing needed to confirm that, but before chunk loading there was no issue with crashing..... this is very confusing

**Comment by IRicTheCoder** [comment] 2024-09-26 17:32
Yeah the cubes are equally problematic, I mentioned spheres as they are more common, but the cubes are exactly the same. 

When checking two blocks as you chunk load (checks are performed when force loading), they have illegal block states (mainly due to the way RFTD generates these cubes/spheres/etc.) which is what it crashing you.

**Comment by ADVM01** [comment] 2024-09-26 18:01
So a new dimension without them should resolve this, right?

**Comment by IRicTheCoder** [comment] 2024-09-26 18:03
I would assume so yes

**Comment by ADVM01** [comment] 2024-09-26 21:21
After a bunch of testing, the cause was definently the giant dirt structures. I hope this thread helps someone out :) Thanks!

**Comment by IRicTheCoder** [comment] 2024-09-26 21:34
The issue is normally always available, I will close it so we know it has been processed. However this did get me the idea to look more into maybe removing those dirt things all together if possible. Thank you!

**Closed as completed by IRicTheCoder** 2024-09-26 21:34 UTC
