### ISSUE TITLE
Immortal Wilden Chimera (thanks to Draconic Mob Grinder)

### ISSUE THREAD

**Issue by godrage** [ChosenArchitect/Project-Architect-2#149] opened 2024-08-18 12:02 UTC
**Describe the bug**
-> Spawning a wilden chimera (via ritual with augments) inside a Draconic Mob Grinder Area leads to the Wilden Chimera instantly going to 0 life without dying, transitioning to stage 2 and being completely immortal and unkillable (even with console commands).

**To Reproduce**
1. spawn wilden chimera in mob farm
2. switch on draconic evolution mob grinder
3. watch chimera get to 0 hp
4. be unable to kill or despawn the critter

**Expected behavior**
-> either kill the chimera instantly or the stage transition should heal it back to the some threshold for the stages to resume?
-> otherwise mob grinders should not damage it at all

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
-> 3.2
**Modpack Launcher Used**
-> Ftb App
**Ram Allocated**
-> 9Gb

PS i am aware it is probably something the author of ars nouveau should/could fix :)

**Comment by James103** [comment] 2024-08-18 22:33
What do you get when you run `/data get entity` on the bugged-out/immortal Warden Chimera?

**Comment by Probi42** [comment] 2024-08-20 00:35
i got the same problem, and as it seems the health value becomes NaN

**Comment by IRicTheCoder** [comment] 2024-08-20 00:49
This seems to happen to any mob, more frequently on bosses, mainly because of immunities and regens, for what I could figure out, I did provide a potential fix in #154 so when Chosen has the chance to look at it, might get implemented.

It should at least prevent it, which it has been for all my tests, however, might also fix the broken ones.

This is not a problem with Ars Nouveau per say, it is more about the way damage is dealt. You can try to set the health of the monster to 1 (`/data modify entity [UUID/Selector] Health set value 1`) then use kill. Kill doesn't work because it applies damage instead of just deleting the entity and the health is bugged.

*Get the UUID by looking at the entity while writing the command.*

**Comment by IRicTheCoder** [comment] 2024-08-22 02:15
Moved the temporary solution into the older post of this issue and will close this one as a duplicate of #129

**Closed as completed by IRicTheCoder** 2024-08-22 02:15 UTC
Labels: duplicate
