### ISSUE TITLE
Invicible withers sometimes appear when using the Mob Grinder from Draconic Evolution

### ISSUE THREAD

**Issue by M4trixm4n** [ChosenArchitect/Project-Architect-2#129] opened 2024-08-11 15:28 UTC
In any wither farm I made (using wither builder then an Apotheosis spawner), when using the Mob Grinder from Draconic Evolution to kill them, they sometimes become invincible. They will fall to 0 HP and will stay at 0 HP. You can hit them, but they never die. /kill command does not work, as well as some other methods of killing using commands, the entity will not even be found for some.

1. Make any type of wither farm (easiest with Apotheosis spawner) and use the Mob Grinder to kill them
2. Wait, maybe wander around
3. Come back and find some withers that won't die

**Screenshots**
![image](https://github.com/user-attachments/assets/6a10461c-f0bb-4d78-a782-31f65ac8da79)

**Modpack version**
-> 3.2 but happened in 3.1 as well

**Additional context**
-> It was all on a server, that's why I could confirm that even admin couldn't kill them
-> The chunks where the farm was were forceloaded with FTB Chunks, but not chunkloaded, and I'm quite sure I left those chunks at some point
-> You can still yoink those withers with the Mob Yoinkers

**Comment by godrage** [comment] 2024-08-18 12:04
Seems this happens with other bosses aswell (Wilden Chimera in my case)

**Comment by James103** [comment] 2024-08-18 22:34
What do you get when you run `/data get entity` on the affected Withers?

**Comment by IRicTheCoder** [comment] 2024-08-22 02:14
This seems to happen to any mob, more frequently on bosses, mainly because of immunities and regens, for what I could figure out. A fix has been worked on and will be tested, but should be implemented soon if it does work as intended.

This is not a problem with the Mob Grinder or the Wither per say, it is more about the way damage is dealt. You can try to set the health of the monster to 1 (`/data modify entity [UUID/Selector] Health set value 1`) then use kill. Kill doesn't work because it applies damage instead of just deleting the entity and the health is bugged.

*Get the UUID by looking at the entity while writing the command.*

**Comment by IRicTheCoder** [comment] 2024-09-16 06:20
A fix for this has been added in version 4.0, should prevent the mobs from becoming broken, it has been tested and it seems to be working nicely. However, issues might still arise. Closing this as solved for now, feel free to reopen if it keeps happening.

**Closed as completed by IRicTheCoder** 2024-09-16 06:20 UTC
Labels: bug

**Comment by madm1c** [comment] 2024-10-21 14:17
The mob grinder still seems to get stuck when trying to kill a mob captured by the stasis machine. When I reduced the AOE area of the grinder it started to work again.

**Comment by IRicTheCoder** [comment] 2025-02-04 01:39
Mobs captured by the stasis machine are healed by the chamber, so there might be some interference there. Can you kill the mob by hand, if so, than it is not the same as this issue, in which case please open a new issue so we can follow up.
