### ISSUE TITLE
Spawned in Outer Ends Biome when entering End Portal first time

### ISSUE THREAD

**Issue by IamDunge** [ChosenArchitect/Project-Architect-2#201] opened 2024-09-01 15:00 UTC
**Describe the bug**
-> I spawned at 1273, 73, -3 in a "outer_end:primordial_pools" biome my first time entering the end with no way to leave the end

**To Reproduce**
1. Light up end portal and walk through
2. Spawn 1300 blocks away from the dragon for unknown reason
3. ??
4. ??

**Expected behavior**
-> Spawn in the end at or around 0,0 to do the dragon fight and have a way out of the end without flying over several hundred blocks of void to get to the arena from the outer end 

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

![image](https://github.com/user-attachments/assets/40abdb10-1bb2-4d8e-8826-b3dd8e3f37af) - Spawn house structure
![image](https://github.com/user-attachments/assets/c05cf810-dfd9-4525-b3f6-44f7656330c5) - Exact end spawn location
![image](https://github.com/user-attachments/assets/710a9c77-768f-41d4-ad4d-b8983aee013d) - Gap i'd have to clear to leave the end

**Modpack version**
-> 3.6
**Java Version**
-> 1.20.1
**Modpack Launcher Used**
-> CurseForge
**Ram Allocated**
-> somewhere around 11gb

**Additional context**
-> I don't actually know if this is intended or not, maybe I just completely missed how I'm supposed to get to the dragon, but if it is intended it was a gigantic letdown having to cheat to get to the dragon fight especially with how cool the arena is.

**Comment by IRicTheCoder** [comment] 2024-09-01 15:05
This is caused by a mod called End's Phantasm, and it is intended, in the normal progression of the quests you should already be able to fly when going to the end, so reaching the center island shouldn't be an issue. You can also find a End Gateway (they spawn on the outer islands) that should take you to the center island, so you don't need to fly per say in order to get there.

There shouldn't be the need to cheat to get to the dragon, but I get your frustration with it.

**Comment by IamDunge** [comment] 2024-09-02 13:43
> This is caused by a mod called End's Phantasm, and it is intended, in the normal progression of the quests you should already be able to fly when going to the end, so reaching the center island shouldn't be an issue. You can also find a End Gateway (they spawn on the outer islands) that should take you to the center island, so you don't need to fly per say in order to get there.
> 
> There shouldn't be the need to cheat to get to the dragon, but I get your frustration with it.

LOL I completely ignored the quests on my speedrun to make an enderman farm. My bad, reading through them now its very clear how to progress. Wish I removed that mod from the pack though, I really don't get the point of it.

**Comment by IRicTheCoder** [comment] 2024-09-02 13:55
> > This is caused by a mod called End's Phantasm, and it is intended, in the normal progression of the quests you should already be able to fly when going to the end, so reaching the center island shouldn't be an issue. You can also find a End Gateway (they spawn on the outer islands) that should take you to the center island, so you don't need to fly per say in order to get there.
> > There shouldn't be the need to cheat to get to the dragon, but I get your frustration with it.
> 
> LOL I completely ignored the quests on my speedrun to make an enderman farm. My bad, reading through them now its very clear how to progress. Wish I removed that mod from the pack though, I really don't get the point of it.

Well the logic is simple, besides adding new things, the idea is that you can go to the end and farm islands without having to intentionally fight the dragon, I personally like that idea, it also makes the End theoretically harder if you don't have the means to leave, which you can with an Warp Stone or many other teleportation items in the modpack.

However, I believe the config of the mod lets you change it back to spawning on the Dragon's island. 

As the issue seems to be resolved, I will close it. Thank you!

**Closed as completed by IRicTheCoder** 2024-09-02 13:55 UTC
