### ISSUE TITLE
Anything ProjectE or Project Expansion related stops working when player logs off the server

### ISSUE THREAD

**Issue by Dony562** [ChosenArchitect/Project-Architect-2#175] opened 2024-08-25 09:24 UTC
**Describe the bug**
->We have a couple things that are automated and fed by EMC links that stop working when the player that the link is linked to logs off.

**To Reproduce**
1. 
2. 
3. 
4. 

**Expected behavior**
->EMC automation should work when a player is offline.

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->3.3
**Java Version**
->1.20.1
**Modpack Launcher Used**
->CurseForge
**Ram Allocated**
->

**Additional context**
->

**Comment by IRicTheCoder** [comment] 2024-08-25 11:06
This seems to be an issue with Project Expansion itself, it has been reported to them and apparently should have been fixed. Are the chunks where the Link is loaded? Are other players besides the owner of the link online?

An alternative fix, is to pipe everything into a chest, then from the chest into the link, that way it should buffer the items while the player is offline, and update it then they get online.

If you have the chance, could you test using a transmutation interface instead of a EMC Link?

**Comment by Dony562** [comment] 2024-08-25 21:41
The chunks are loaded. I was online when the player that put the link down went offline and noticed any links that they put down stop working. The transmutation interface also stops working.

**Comment by IRicTheCoder** [comment] 2024-08-25 22:55
That is unfortunate, it is a bug with project expansion, but according to them it should have been fixed already, so before opening an issue there, I would like to check configs and do more testing, thank you for your feedback and the info provided

**Comment by DoomSquirter** [comment] 2024-08-27 10:13
just to throw this in since nobody mentioned it
by default, the ftb chunks mod is set not to offline chunkload unless the person has a rank set or the config is set to always
I haven't updated the pack yet.  still on 3.3 but next 2 updates don't show any projecte related updates
Noticed that someone on our server, even after changing the aforementioned ftb chunks config option, their emc stuff does not update when they are offline

edit:
https://github.com/DonovanDMC/ProjectExpansion/issues/137
it does not look like this is "fixed" on their end.  it's not a bug.  it's intended behavior.
this is going to make finishing this pack very painful, especially with all the single block MK collectors disabled
best I've been able to obtain is about 250-500k emc /s with draconium ore

**Comment by IRicTheCoder** [comment] 2024-08-27 10:25
@DoomSquirter Thanks for your feedback, this was mentioned before on Discord, but it is still important info. Also not sure how I missed that bug report, because the one I saw said it was fixed and that it should be working now. This is unfortunate, makes doing certain farms on this pack very hard.

As a side note, generation gets easier once you get into the Archi- blocks, starting with the Archimeat.

**Comment by DoomSquirter** [comment] 2024-08-27 18:47
I don't want to take up the issue here but I don't see how doing the archimeat helps.  a lot of the things the plushies are made with are non automatable.  the only plushie I've been able to fully automate is the elder guardian one so far.
edit: I'm dumb.  I just realized my mistake.  yeah that seems like a great way.  thanks for the tip

**Comment by IRicTheCoder** [comment] 2024-08-30 17:08
Since the mod author states this is intended, and the reason does make since, will close this issue as intended.

**Closed as completed by IRicTheCoder** 2024-08-30 17:08 UTC
Labels: bug, mod issue
