### ISSUE TITLE
Magmator Nitro only generates 10kFE/t when tooltip says 40kFE/t

### ISSUE THREAD

**Issue by mouro001** [ChosenArchitect/Project-Architect-2#173] opened 2024-08-24 14:25 UTC
**Describe the bug**
-> The tooltip for Magmator Nitro says "Generates: 40k FE/t" but when plugging a Energy Meter to it, it only generates 10k FE/t

**To Reproduce**
1. Place a Magmator Nitro
2. Place a Energy Meter configured to take input from the Magmator
3. Configure Output

**Expected behavior**
-> Energy Meter should say 40k FE/t

**Screenshots**
![image](https://github.com/user-attachments/assets/38d4a395-7faf-4917-a341-1bb5b19d1c1d)

**Modpack version**
-> 3.5
**Java Version**
-> 17.0.8
**Modpack Launcher Used**
-> Prism
**Ram Allocated**
-> 8192MB

**Comment by James103** [comment] 2024-08-24 18:36
This may be because lava is not hot enough for the Magmator to work at full efficiency.
Are there any other fuels which would work in the Magmator? If so, have you tried using them?

**Comment by mouro001** [comment] 2024-08-24 18:38
seems like you're right, however there doesn't seem like there's hotter fluids 
![image](https://github.com/user-attachments/assets/d59b22f3-43ed-4bd2-ab4c-a685ca54eeef)

**Comment by IRicTheCoder** [comment] 2024-08-25 00:54
This is the issue with mods expecting other mods to exist, there might be fluids that are considerably hotter than lava on the pack but not recognized by the magmator, maybe another fluid can be added manually to it, need to investigate.

Labelling this as enhancement to know to look for more fluids to add to it.

**Comment by LuciusV** [comment] 2024-09-09 10:44
This is very old default config bug of powah, has been in every modpack.
change 
"magmatic_fluids": {
			"minecraft:lava": 10000
		}
to 40000 in powah.json5

**Comment by IRicTheCoder** [comment] 2024-09-09 12:26
> This is very old default config bug of powah, has been in every modpack. change "magmatic_fluids": { "minecraft:lava": 10000 } to 40000 in powah.json5

That is not a config bug, `Powah` was designed to integrate with multiple mods, if you have those mods it gets added automatically to the config. The config is also present for modpack makers to add multiple options based on the modpack design.

Which we have looked into adding, so potentially next updates will have new fluids at different rates.

So I would say lava staying like that is intended and not a bug in the design/config.

**Comment by IRicTheCoder** [comment] 2024-09-16 06:27
New fluids have been added to the magmator, there are variations all the way up to the maximum of 40k/t. Closing this as solved/added.

**Closed as completed by IRicTheCoder** 2024-09-16 06:27 UTC
Labels: enhancement
