### ISSUE TITLE
Log Spam & Modular Routers Not Breaking

### ISSUE THREAD

**Issue by zeziba** [ChosenArchitect/Project-Architect-2#189] opened 2024-08-28 15:45 UTC
**Describe the bug**
While reading the logs to see what was causing the modular routers to be unable to be broken I noticed that the spam of the log.

Seems to be the same bug of issue #165 & #179 

The log spam is as follows

```
[10:37:38] [Render thread/WARN]: null nbt in ETF.
[10:37:38] [Render thread/WARN]: null nbt in ETF.
[10:37:38] [Render thread/WARN]: null nbt in ETF.
[10:37:38] [Render thread/WARN]: null nbt in ETF.
[10:37:38] [Render thread/WARN]: null nbt in ETF.
[10:37:38] [Render thread/WARN]: null nbt in ETF.
[10:37:38] [Render thread/WARN]: null nbt in ETF.
```

**To Reproduce**
No idea what caused the spam to start.

**Expected behavior**
No 30k+ lines of spwm

**Modpack version**
-> 3.5
**Java Version**
-> 
**Modpack Launcher Used**
-> curseforge
**Ram Allocated**
-> 12Gb

**Additional context**

[latest.log](https://github.com/user-attachments/files/16785765/latest.log)

Spam started after these lines

```
[08:35:25] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Architech Or Engineer]'/minecraft:overworld
[08:35:25] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Architech Or Engineer]'/minecraft:the_nether
[08:35:25] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Architech Or Engineer]'/deeperdarker:otherside
[08:35:25] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Architech Or Engineer]'/the_bumblezone:the_bumblezone
[08:35:25] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Architech Or Engineer]'/minecraft:the_end
[08:35:25] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Architech Or Engineer]'/ae2:spatial_storage
[08:35:26] [Render thread/INFO]: moze_intel.projecte.gameObjs.gui.GUITransmutation
[08:35:27] [Render thread/INFO]: net.p3pp3rf1y.sophisticatedbackpacks.client.gui.BackpackScreen
[08:35:30] [Render thread/INFO]: moze_intel.projecte.gameObjs.gui.GUITransmutation
[08:35:37] [Render thread/ERROR]: Deleting stream buffers: Invalid operation.
[08:35:44] [Render thread/INFO]: net.p3pp3rf1y.sophisticatedbackpacks.client.gui.BackpackScreen
[08:35:47] [Render thread/INFO]: moze_intel.projecte.gameObjs.gui.GUITransmutation
[08:35:58] [Render thread/INFO]: moze_intel.projecte.gameObjs.gui.GUITransmutation
[08:36:00] [Render thread/INFO]: net.p3pp3rf1y.sophisticatedbackpacks.client.gui.BackpackScreen
[08:36:32] [Render thread/INFO]: mcjty.rftoolsstorage.modules.scanner.client.GuiStorageScanner
[08:36:38] [Render thread/INFO]: Container is missing!
[08:36:59] [Render thread/INFO]: net.minecraft.client.gui.screens.inventory.InventoryScreen
[08:37:00] [Render thread/INFO]: top.theillusivec4.curios.client.gui.CuriosScreenV2
[08:37:02] [Render thread/ERROR]: Deleting stream buffers: Invalid operation.
[08:37:39] [Render thread/INFO]: net.minecraft.client.gui.screens.inventory.InventoryScreen
[08:38:01] [Render thread/INFO]: net.minecraft.client.gui.screens.inventory.InventoryScreen
[08:38:02] [Render thread/INFO]: net.p3pp3rf1y.sophisticatedbackpacks.client.gui.BackpackScreen
[08:38:06] [Render thread/INFO]: net.minecraft.client.gui.screens.inventory.InventoryScreen
[08:38:07] [Render thread/INFO]: net.p3pp3rf1y.sophisticatedbackpacks.client.gui.BackpackScreen
[08:38:12] [Render thread/INFO]: net.p3pp3rf1y.sophisticatedbackpacks.client.gui.BackpackScreen
[08:38:40] [Render thread/WARN]: null nbt in ETF.
[08:38:40] [Render thread/WARN]: null nbt in ETF.
[08:38:42] [Render thread/WARN]: null nbt in ETF.
```

**Comment by IRicTheCoder** [comment] 2024-08-28 15:53
Modular Routers not breaking is a known issue, been reported a few times. Use TinyTNT or turn on cheats to break it. It will be fixed in the next update.

As for the `null nbt in ETF` we haven't found the cause it, it seems to appear randomly and never on the same situations. Most likely will add a mod to clean the log from messages like that.

**Comment by zeziba** [comment] 2024-08-28 16:19
@IRicTheCoder Sounds good, was looking at the ETF mod and was thinking about it as when I first created my world there were invisible pigs, not with the potion effect but just a floating group of pixels and a shadow. Didn't care at the time but now that I am looking at the logs it might be because of the invisible pigs. Also did not notice any other entity yet to not have their textures.

Also, the trials in had invisible spiders but I do not know if they had the effect as I did not see the potion effect particles.

**Comment by IRicTheCoder** [comment] 2024-08-28 16:23
Trials spiders should be fine, they are meant to be invisible. As for the pig that is a good idea, try disabling the `Porkier Pigs` texture pack and test it.

**Comment by zeziba** [comment] 2024-08-28 19:32
@IRicTheCoder  disabled the porkier packs and the spam is gone now, still get the warning log though but only 2 right off the bat and not continuing like before.

Also, the invisible pigs showed back up as well.

Will play for a bit to see if it starts back up.


[latest.log](https://github.com/user-attachments/files/16788114/latest.log)

**Comment by zeziba** [comment] 2024-08-28 20:51
Still doing it after an hour or play, only at 11k lines in the log file where after an hour before was nearly 40k so it is an improvement.

**Comment by IRicTheCoder** [comment] 2024-08-28 21:31
So I can assume other things are causing that NBT issue. Maybe there is a way to fix it, so that the packs can stay but the error will be gone. Thanks for testing and for the feedback

**Comment by zeziba** [comment] 2024-08-29 00:19
I am writing a request/issue to the EFT github about changing the `ETFUtils2.logWarn("null nbt in ETF");` to be a little more verbose so that it is easier to identify what is causing the issue as the error message is just non-sense atm.

That way it will be easier to utilize the ETF mod.

I have the issue here https://github.com/Traben-0/Entity_Texture_Features/issues/302

**Comment by IRicTheCoder** [comment] 2024-08-29 00:28
Thank you I appreciate that, in any case looking of it can be fixed on the pack for now is still on my list, low priority though, as it is just annoying doesn't really break anything.

**Comment by IRicTheCoder** [comment] 2024-08-30 17:05
The NBT issue should be less frequent, still trying to pin point the causes though. Thank you for posting the issue in ETF's github. As for the modular routers, they are breakable in 3.6 just don't leave items with NBTs inside the buffer when breaking. Closing this as fixed.

**Closed as completed by IRicTheCoder** 2024-08-30 17:05 UTC
Labels: bug, unsure
