### ISSUE TITLE
The modpack crashes when starting

### ISSUE THREAD

**Issue by pedro-assuncao** [ChosenArchitect/Project-Architect-2#240] opened 2024-09-21 16:37 UTC
**Describe the bug**
-> The modpack won't open, I click on “play” in the launcher and after 2 seconds the modpack crashes. Exit code 1

**To Reproduce**
1. I click on “Play” in the curseforge
2. I click on “Play” in the launcher
3. After 2 seconds of loading, the modpack crashes

**Expected behavior**
-> I tried checking the crash log, and I see the Extrasound mod a few times.

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
![image](https://github.com/user-attachments/assets/51c389bf-03e5-4c62-8450-b4942a5107b9)

**Modpack version**
-> 4.2
**Java Version**
-> (build 1.8.0_421-b09)
**Modpack Launcher Used**
-> CurseForge
**Ram Allocated**
-> 22.048MB (22GB)

**Additional context**
->I've updated all the drivers, processor, video card and motherboard. 
Ryzen 7800X3D
RTX 3090
[debug.log](https://github.com/user-attachments/files/17085039/debug.log)
[debug-1.log.gz](https://github.com/user-attachments/files/17085040/debug-1.log.gz)
[latest.log](https://github.com/user-attachments/files/17085041/latest.log)

**Comment by IRicTheCoder** [comment] 2024-09-21 16:52
Is there a report inside the `crash-reports` folder? That is more important when trying to find out the reason of a crash

**Comment by pedro-assuncao** [comment] 2024-09-21 17:16
I don't see this folder, I don't think it has generated this “crash-report” folder yet. The game closes very quickly. I've played other modpacks from the same version of minecraft or forge, and they start normally.
![image](https://github.com/user-attachments/assets/579b7379-9afb-4e29-94e0-7af0beeb2218)

**Comment by IRicTheCoder** [comment] 2024-09-21 17:23
Based on that the pack is not even executing, so there might be an issue in the Minecraft Launcher

Click the three dots on the side of the search bar and click repair install and try again, here a picture to explain it
![image](https://github.com/user-attachments/assets/4fa0c517-83f1-471e-9676-9ab743f1c6a6)

**Comment by pedro-assuncao** [comment] 2024-09-21 17:31
It worked, thank you very much. I never thought it was this, as I was playing other modpacks on the same version of minecraft and forge. Thank you for your time

**Comment by IRicTheCoder** [comment] 2024-09-21 17:31
No worries, since the issue is resolved I will close this. Have fun!

**Closed as completed by IRicTheCoder** 2024-09-21 17:31 UTC
